SELECT BA,SUM(TUTAR),SUM(MIKTAR),CAST(SUM(ROUND(DOVIZTUT,2)) AS DECIMAL(28,2)),CAST(SUM(ROUND(FIRMADOVTUT,2)) AS DECIMAL(28,2)), ISNULL(DOVIZTIP,0)

 FROM MUHFIS WITH (NOLOCK)

 INNER JOIN MUPLANEK  WITH (NOLOCK)  ON (KOD = HES_KOD)

 WHERE HES_KOD = '102-01-002'

 AND (TARIH BETWEEN '01/01/2025'

 AND '04/25/2025')

 AND (SUBE_KODU=0)

 GROUP BY  ISNULL(DOVIZTIP,0)

,BA

 ORDER BY  ISNULL(DOVIZTIP,0)

,BA
